doctrine:
  orm:
    auto_mapping: true
    mappings:
      TextBlock:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/block-bundle/src/Domain/Block/Entity'
        prefix: Zentlix\BlockBundle\Domain\Block\Entity